#!/usr/bin/env bash
# shellcheck shell=bash disable=SC1091,SC2039,SC2166
#
#  id.sh
#  Created: 2024/04/16
#  Altered: 2024/08/16
#
#  Copyright (c) 2022-2024, Vilmar Catafesta <vcatafesta@gmail.com>
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions
#  are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
#  IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
#  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
#  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
#  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
#  NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
#  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
#  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
#  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
#  THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
##############################################################################
#export LANGUAGE=pt_BR
export TEXTDOMAINDIR=/usr/share/locale
export TEXTDOMAIN=chili-makebash

#debug
export PS4='${red}${0##*/}${green}[$FUNCNAME]${pink}[$LINENO]${reset} '
#set -x
#set -e
shopt -s extglob

#system
readonly APP="${0##*/}"
readonly _VERSION_='1.0.0-20240416'
readonly distro=$(uname -n)
readonly DEPENDENCIES=(grep)

#resourceClass

option="$1"
url="$2"
class="${url/https:\/\//}"
class="${class/\//__}"

# Função de ajuda
function exibir_ajuda() {
    echo "Uso: $0 [OPÇÃO]"
    echo "Opções disponíveis:"
    echo "  --id | -i       : Executa big_appid"
    echo "  -id-web | -w    : Executa big_appid_web"
    echo "  --help | -h     : Exibe esta mensagem de ajuda"
}

big_appid() {
WAYLAND_DEBUG=1 \
   brave \
      --class="$class" \
      --profile-directory=Default \
      --app="$url" \
      |& grep -E 'xdg_toplevel@[0-9]+\.set_app_id'

}

big_appid_web() {
WAYLAND_DEBUG=1 "$@" |& grep -E 'xdg_toplevel@*.*set_app_id'
}

# Verifica a opção passada
case "$1" in
    --id | -i)
        big_appid
        ;;
    -id-web | -w)
        big_appid_web
        ;;
    --help | -h)
        exibir_ajuda
        ;;
    *)
        echo "Opção inválida. Use --help para obter ajuda."
        ;;
esac
